# 需求:往控制台中输出Hello World,Hello Python(快捷键:ctl+/)
print("##################")
print("## 白 日 依 山 尽 ##")
print("## 黄 河 入 海 流 ##")
print("## 欲 穷 千 里 目 ##")
print("## 更 上 一 层 楼 ##")
print("##################")
